### ISSUE TITLE
Use of GEE packages for PML v2 download from GEE

### ISSUE THREAD

**Issue by mabesa** [gee-hydro/gee_docs#1]
Dear PML developers

I would like to use the PML data for estimating the water balance in a couple of basins but I cannot manage to download it from GEE. 

I adapted your example code linked here (https://github.com/gee-hydro/gee_PML) where you use pkg_export.js. The code errors with the message that it doesn't find pkg_export.js so I came here to try to connect it to my GEE workspace but the link https://code.earthengine.google.com/?accept_repo=users/kongdd/public doesn't lead me to the package. Could you maybe help me with the access to the PML data?

With best regards

**Comment by kongdd** [comment]
please give your gee link

**Comment by mabesa** [comment]
Thank you for the quick reply! What is the gee link? Is the gee username sufficient?

**Comment by kongdd** [comment]
The following script works. Enjoy it.
```javascript
/**
* Copyright (c) 2019 Dongdong Kong. All rights reserved.
* This work is licensed under the terms of the MIT license.
* For a copy, see <https://opensource.org/licenses/MIT>.
*/
var col = ee.ImageCollection("projects/pml_evapotranspiration/PML/OUTPUT/PML_V2_8day_v017");
col = col.select([0, 1, 2, 3, 4]); // rm the qc band, [GPP, Ec, Es, Ei, ET_water]
// print(col.limit(3));

var pkg_export = require('users/kongdd/pkgs:pkg_export.js');
// export parameters
var options = {
  type: "drive",
  range: [-180, -60, 180, 90], // [73, 25, 105, 40],
  cellsize: 1 / 240,
  // crsTransform : [463.312716528, 0, -20015109.354, 0, -463.312716527,10007554.677], // prj.crsTransform;
  // scale    : 463.3127165275, // prj.scale
  crs: 'EPSG:4326', // 'SR-ORG:6974', // EPSG:4326
  folder: 'PMLV2'
};
pkg_export.ExportImgCol(col.limit(3), 'PMLV2_v017_GLDASV21_8d_', options);
```
https://code.earthengine.google.com/544f2e2b92c6150b88fe85156a463a7d

Please modify the last line to filter the period that you need.
